language: python

# needed to build python-rhsm
before_install:
 - "sudo apt-get install gcc libssl-dev m2crypto"
 - "git clone https://github.com/candlepin/python-rhsm; cd python-rhsm; python setup.py install; cd .."

virtualenv:
  system_site_packages: true

script:
  - "./scripts/ceilometer_katello_dispatcher_pr_ci.sh"

